<div class="col-lg-12">

            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href="<?= $this->baseUrl() ?>/usuario/">
                        <span class="pull-left"><i class="fa fa-arrow-circle-left"></i></span>&nbsp;</a> Cadastro de Usuário 
                </div>
                <div class="panel-body" style="padding: 45px;">
                    <div class="row">
                        <?php echo $this->formUsuario ?>      
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
</div>
<!-- /.col-lg-12 -->