<?php
    $request = Zend_Controller_Front::getInstance()->getRequest();
    $controller = $request->getControllerName();
?>

<?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
<?php foreach ($flashMessenger->getMessages() as $msg): ?>
    <?php echo $msg ?>
<?php endforeach; ?>

<div class="col-lg-12">
<p>
  <a href="<?= $this->baseUrl() ?>/usuario/cadastrar/">
    <button type="button" class="btn btn-primary">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Cadastrar Usuário
    </button></a>
</p>

                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Lista de Estilos
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <?php echo $this->paginator?>
                                <table class="table table-striped table-bordered table-hover" id="dataTable">
                                    <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Nome</th>
                                            <th>Email</th>
                                            <th>permissão</th>
                                            <th>Ação</th>
                                        </tr>
                                    </thead>                                    
                                    <tbody>
                                        <?php foreach($this->list as $obj): ?>
                                        <tr class="gradeU">
                                            <td>
                                                <?= $obj->cli_codigo ?>
                                            </td>
                                            <td class="center">
                                                <?= $obj->cli_nome ?>
                                            </td>
                                            <td>
                                                <?= $obj->cli_email ?>
                                            </td>
                                            <td> <?= $obj->cli_permissao ?>
                                            </td>
                                            <td class="center">
                                                <a class="remove_item" href="javascript:void(0);" controller="<?php echo $controller?>" id="<?php echo $obj->cli_codigo ?>">
                                                <button type="button" class="btn btn-danger">
                                                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                                </button>
                                                </a>
                                                <a href="<?php echo $this->baseUrl()?>/usuario/editar/id/<?php echo $obj->cli_codigo?>">
                                                <button type="button" class="btn btn-info">
                                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                                </button>
                                                </a>
                                            </td>
                                        </tr>
                                        <? endforeach; ?>  
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->

<script>
    // $(document).ready(function() {
    //     $('#dataTables').DataTable({
    //             responsive: true
    //     });
    // });
 </script>
