<div class="col-lg-12">

<p>
<div class="bs-example" data-example-id="split-button-dropdown">
    <div class="btn-group">

      <a href="<?= $this->baseUrl() ?>/usuario/">  
      <button type="button" class="btn btn-default">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Voltar</button>
      </a>
    </div><!-- /btn-group -->
  </div>

</p>

            <div class="panel panel-default">
                <div class="panel-heading">
                    Editar Usuário 
                </div>
                <div class="panel-body" style="padding: 45px;">
                    <div class="row">
                        <?php echo $this->formUsuario ?>      
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
</div>
<!-- /.col-lg-12 -->
