<p>
    <a href="<?= $this->baseUrl() ?>/cliente/"><button type="button" class="btn btn-toolbar"><i class="icon-chevron-left"> Voltar</i></button></a>
</p>

<div class="col-lg-12">

            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href="<?= $this->baseUrl() ?>/estilos/">
                        <span class="pull-left"><i class="fa fa-arrow-circle-left"></i></span>&nbsp;</a> Cadastro de Estilo 
                </div>
                <div class="panel-body" style="padding: 45px;">
                    <div class="row">
                        <?php echo $this->formCliente ?>      
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
</div>
<!-- /.col-lg-12 -->

            
        