<?php
    $auth = Zend_Auth::getInstance();
    $identity = $auth->getIdentity();
?>


<div class="panel panel-default well">
  <div class="panel-body">
    <img  style="float: left; margin-right: 15px; max-width: 128px" src="<?php echo $this->baseUrl()?>/img/profile.png" alt="..." class="img-topo-perfil img-thumbnail"></br>
    Olá: <span class="badge" style="text-transform: uppercase"><?php echo $identity->cli_nome ?></span><br/>
    Permissão: <span class="badge" style="text-transform: uppercase"><?php echo $identity->cli_permissao ?></span><br/>
    Email: <span class="badge" style="text-transform: uppercase"><?php echo $identity->cli_email ?></span><br/>
    WhatsApp: <span class="badge" style="text-transform: uppercase"><?php echo $identity->cli_telefone ?></span><br/>

  </div>
</div>

<?php if($identity->cli_permissao=="administrador"|| $identity->cli_permissao=="administrador-agenda"):?>          
<!-- /.row -->
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-envelope-o fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"><?php echo $this->totalMailing?></div>
                                    <div>Mailing</div>
                                </div>
                            </div>
                        </div>
                        <a href="<?php echo $this->baseUrl()?>/eventos/geral">
                            <div class="panel-footer">
                                <span class="pull-left">Ver Detalhes</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>


                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-group fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"><?php echo $this->totalEventos?></div>
                                    <div>Eventos</div>
                                </div>
                            </div>
                        </div>
                        <a href="<?php echo $this->baseUrl()?>/eventos/">
                            <div class="panel-footer">
                                <span class="pull-left">Ver Detalhes</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-yellow">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-music fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"><?php echo $this->totalBandas?></div>
                                    <div>Bandas</div>
                                </div>
                            </div>
                        </div>
                        <a href="<?php echo $this->baseUrl()?>/banda/">
                            <div class="panel-footer">
                                <span class="pull-left">Ver Detalhes</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <!-- <div class="col-lg-3 col-md-6">
                    <div class="panel panel-yellow">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-shopping-cart fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">124</div>
                                    <div>New Orders!</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-support fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">13</div>
                                    <div>Support Tickets!</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div> -->
            </div>
            <!-- /.row -->
<?php endif;?>     