<!-- Modal -->
<div class="modal fade" id="myModalMap" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content map" style="width: 850px;margin-left: -21%;">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Localizar endereço</h4>
      </div>
        <div class="modal-body2">
          <p id="alert-content">
              <iframe id="map_endereco" src="<?=$this->baseUrl()?>/endereco/map" width="840" height="560" scrolling="no" ></iframe>
          </p>
        </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        <button type="button" id="salvar_endereco" data-dismiss="modal" class="btn btn-primary">Salvar endereço</button>
      </div>
    </div>
  </div>
</div>