<!DOCTYPE html>
<html lang="pt_br">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Discípulos em João Pessoa</title>

    <!-- Bootstrap Core CSS -->
    <link href="<?= $this->baseUrl() ?>/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="<?= $this->baseUrl() ?>/bootstrapvalidator/dist/css/bootstrapValidator.min.css"/>

    <!-- MetisMenu CSS -->
    <link href="<?= $this->baseUrl() ?>/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="<?= $this->baseUrl() ?>/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="<?= $this->baseUrl() ?>/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<style type="text/css">

p{
    text-align: center;
    margin-bottom: 10px;
    margin-top: 10px;
}
</style>

<body>

    <div class="container">
        <div class="row">

            <?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
            <?php foreach ($flashMessenger->getMessages() as $msg): ?>
                <?php echo $msg ?>
            <?php endforeach; ?>
            
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Preencha seus dados abaixo</h3>
                    </div>
                    <div class="panel-body">
                        
                        
                                <?php echo $this->form?>

                                
                                
                                <p>ou </p>
                                <a href="<?php echo $this->baseUrl()?>/login">
                                  <button type="button" id="btn-cadastro" class="btn btn-lg btn-default btn-block" >Cancelar</button>
                                </a>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- jQuery -->
    <script src="<?= $this->baseUrl() ?>/bower_components/jquery/dist/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?= $this->baseUrl() ?>/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="<?= $this->baseUrl() ?>/bower_components/metisMenu/dist/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="<?= $this->baseUrl() ?>/dist/js/sb-admin-2.js"></script>

    <script type="text/javascript" src="<?=$this->baseUrl()?>/bootstrapvalidator/dist/js/bootstrapValidator.min.js"></script>
    <script type="text/javascript" src="<?=$this->baseUrl()?>/bootstrapvalidator/src/js/language/pt_BR.js"></script>

    <script src="<?= $this->baseUrl() ?>/js_system/jquery-login.js"></script>





</body>

</html>